### PR TITLE
chore(dependencies): remove lodash's pre-method packages

### LINKED ISSUE #26: Do not use individual lodash packages
https://github.com/iansinnott/react-string-replace/blob/master/package.json#L34-L37

```
  "dependencies": {
    "lodash.escaperegexp": "^4.1.1",
    "lodash.flatten": "^4.2.0",
    "lodash.isregexp": "^4.0.1",
    "lodash.isstring": "^4.0.1"
  },
```

Consider using:

https://github.com/lodash/babel-plugin-lodash (for package dev)
https://github.com/lodash/lodash-webpack-plugin (for app development)

Per method packages have been discontinued, https://github.com/lodash/lodash/wiki/Roadmap.

> Discontinue per method packages in favor of modular lodash

### PR DESCRIPTION
**Pull request by geminiyellow**
Depending directly on lodash packages isn't supported by lodash anymore.

Close #26

### CODE REVIEW

**Comment by iansinnott** [comment]
Awesome, thanks for the PR. Does this mean we need to upgrade to lodash 5 or is it fine to stay on 4.x?

**Comment by geminiyellow** [comment]
@iansinnott thanks for your great work.

still safe before lodash 5 release. 😈

**Comment by geminiyellow** [comment]
@iansinnott 

and comment from @jdalton in lodash/lodash-webpack-plugin/issues/101

> @jdalton commented on 17 Mar
> 
> That would require folks having both packages which is an unknown. I'm also not continuing the individual packages beyond v4 so not wanting to put anymore time into them feature wise.

**Comment by iansinnott** [comment]
Sounds good to me. v0.4.1

**Pull request merged**
