### PR TITLE
Added working version, updated readme, added tests.

### LINKED ISSUE #6: Consider supporting the full String.prototype.replace API
Not sure how big a lift this would be, but something to think about.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

### PR DESCRIPTION
**Pull request by pejrak**
Resolves #6 , but may be introducing breaking changes compared to the previous package versions, which depended on the `index` being the second argument of replacer function.

### CODE REVIEW

**Comment by iansinnott** [comment]
Awesome! Thanks @pejrak. You're right about the `index` so this will need to be released as a new _major_ version, which is totally fine.

**Comment by iansinnott** [comment]
@pejrak you feeling good about this one? Maybe we release 1.0 with these changes?

**Comment by pejrak** [comment]
@iansinnott This is good from functionality stand-point, have been using it in a project since adding. The readme should be good, the only thing I did not fully check is the full example with node server. Are you able to execute that?

**Comment by iansinnott** [comment]
@pejrak ah, thanks for the reminder. I will look into that and fix it as need be

**Comment by rpearce** [comment]
Doesn't look like this has any movement, but I solved the same problem today and have this functionality at https://github.com/rpearce/flexible-string-replace

**Comment by iansinnott** [comment]
Thanks @rpearce. Yeah this one seems to have fallen though the cracks. Going to close it out now as it's two years old

**Comment by rpearce** [comment]
Thanks @iansinnott . @pejrak, if you'd like to be added as a contributor on https://github.com/rpearce/flexible-string-replace, let me know, as your alternative solution & mine were almost identical, and if you still have this problem, perhaps we can iterate there together.

**Pull request closed without merging**
